### ISSUE TITLE
PCB Marking and BOM do not match for R4 and R6

### ISSUE THREAD

**Issue by hexbus** [go4retro/Philharmonic12#1]
PCB has R6 being a 470 ohm and R4 being a 4K7 resistor, but the BOM has R1,2,3,4 being 470 ohm and R5,6 being 4K7.

So, is the BOM or the PCB correct?  Thanks!

**Comment by go4retro** [comment]
BOM is right, but the R4/R6 was placed wrong on the PCB.  I will update.  Check the new PCB PNG for correct labels.  Thanks for finding the error.

**Comment by go4retro** [comment]
Fixed with this commit: https://github.com/go4retro/Philharmonic12/commit/c6d84ed5600dc92936110f36d66de8313380bf22

**Comment by go4retro** [comment]
closing
